# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "worksihope" ]
  pull_request:
    branches: [ "worksihope" ]

jobs:
  checkfiles:
    runs-on: ubuntu-latest
    outputs:
      good: ${{ steps.get_output.outputs.good }}
    steps:
      - uses: actions/checkout@v3
      - name: Check file existence
        continue-on-error: true
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "jest.config.js"
      - name: Set output
        run: |
          echo good=${{ steps.check_files.outcome }} >> $GITHUB_OUTPUT        
  build:
    if: needs.checkfiles.outputs.good == 'success'
    needs: checkfiles
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
